name: xai
channels:
        - conda-forge
        - default
dependencies:
        - python >= 3.9.4
        - pip >= 21.1.1
        - jupyterlab >= 3.0.15
        - seaborn >= 0.11.1
        - pandas >= 1.2.4
        - plotly >= 4.14.3
        - scikit-learn >= 0.24.2
        - shap >= 0.39.0
        - pyarrow >= 4.0.0
        - lightgbm
        - bayesian-optimization >= 1.1.0